# Generated by Django 4.2.10 on 2024-02-24 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backstage", "0003_shoppingcart"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingCartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "cartID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="backstage.shoppingcart",
                    ),
                ),
                (
                    "productID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="backstage.product",
                    ),
                ),
            ],
        ),
    ]
