# Generated by Django 4.2.10 on 2024-02-26 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backstage", "0004_shoppingcartitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "house_number_and_street",
                    models.CharField(
                        max_length=255, verbose_name="House Number and Street"
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Area"
                    ),
                ),
                ("town", models.CharField(max_length=255, verbose_name="Town")),
                (
                    "county",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="County"
                    ),
                ),
                ("postcode", models.CharField(max_length=8, verbose_name="Postcode")),
                (
                    "country",
                    models.CharField(
                        default="United Kingdom", max_length=255, verbose_name="Country"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
    ]
