# Generated by Django 4.2.10 on 2024-02-26 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backstage", "0005_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.JSONField(default=dict)),
                ("address", models.JSONField(default=dict, verbose_name="Address")),
                ("totalCost", models.FloatField(verbose_name=10)),
                (
                    "createTime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Time"),
                ),
                (
                    "finishTime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finish Time"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("cancel", "Cancel"),
                            ("processing", "Processing"),
                            ("delivered", "Delivered"),
                            ("done", "Done"),
                        ],
                        default="unpaid",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "isPaid",
                    models.BooleanField(
                        choices=[(True, "Paid"), (False, "Not Paid")],
                        default=False,
                        verbose_name="Is Paid",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
    ]
